Update System Testing
damorimRG/practical_testing_book pull request #64
Opened 2020-09-12 02:38 UTC by mvgmb

- Restructured file 
- Rewrote text
- Remade `Hands On` example since it was not working

Closes issue #52

2020-09-12 02:52 UTC, t0rr3sp3dr0 requested changes

2020-09-12 02:52 UTC, t0rr3sp3dr0 commented on testgranularity/systemtesting.md
> +![Img](../assets/systemtesting_diagram.png)
It would be better to change the caption from `Img` to something more meaningful.

2020-09-12 03:03 UTC, t0rr3sp3dr0 approved these changes

2020-09-12 03:03 UTC, merged

2020-09-14 20:11 UTC, damorim commented
* Remova esta figura inicial. Não está ajudando.

* Gostei da ideia do gif animado, mas isto pode melhorar. Dá para ver icones de arquivo do desktop e nao da para entender qual a intencao do gif. Seria bem melhor se fosse um video de 15s mostrando o que será feito no hands on e a saida.

* Icon open in colab deve aparecer imediatamente apos "Hands On"

* Vários problemas no notebook:

 + Vc. não explica como este arquivo .robot é criado no colab! Há vários exemplos criando arquivos no colab. Dá uma olhada.
 + Olha o que vc. diz abaixo no texto. O leitor não tem como entender isto. Vc. não oferece contexto do que vai acontecer e para que vc. está fazendo isto. Sem contar, que vc. não explica---mesmo que por alto--o formato deste arquivo.

"We are goinf to test if we are able to change sections in the Practical Testing Book."

 + Em resumo, a execução deveria fazer sentido se eu der "play" em cada um dos passos do notebook.