git-bisect Revision
damorimRG/practical_testing_book pull request #65
Opened 2020-09-12 02:38 UTC by t0rr3sp3dr0

Closes #58

2020-09-12 02:54 UTC, mvgmb commented on debugging/gitbisect.md
> +It is common to make some change on a repository that introduces a bug. And sometimes this bug goes unoticed for a while, but when its detected not always is simple to find the root cause.
Typo "but when **it's** detected not"

2020-09-12 02:56 UTC, mvgmb approved these changes
In general it look fine, according to the _Book Rules_.

2020-09-12 02:57 UTC, mvgmb requested changes

2020-09-12 02:57 UTC, mvgmb commented on debugging/gitbisect.md
> +It is common to make some change on a repository that introduces a bug. And sometimes this bug goes unoticed for a while, but when its detected not always is simple to find the root cause.
Typo "but when it's detected not"

2020-09-12 03:02 UTC, mvgmb approved these changes

2020-09-12 03:03 UTC, merged

2020-09-14 19:51 UTC, damorim commented
Bom trabalho!

Comentários:

* Crie apenas um arquivo .ipynb com todo o conteúdo. Da forma atual, o tutorial não aparece no livro! Coloque o conteudo do arquivo .md dentro do arquivo .ipynb.